elasticsearch:
  image: elasticsearch
  esJavaOpts: -Xmx8g -Xms8g
  resources:
    limits:
      memory: 10Gi
    requests:
      memory: 10Gi
  sysctlInitContainer:
    enabled: false

ingress:
  enabled: true
  tls: true
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hostname: chart-example.local
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
