{{- if .Values.security.networkPolicy.enable -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "cloudshell.fullname" . }}
spec:
  podSelector:
    matchLabels:
      {{- include "cloudshell.selectorLabels" . | nindent 6 }}
  ingress:
  - from:
    - podSelector: {}
  policyTypes:
  - Ingress
{{- end }} 