apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudshell.fullname" . }}
  labels:
    {{- include "cloudshell.labels" . | nindent 4 }}
spec:
  type: {{ .Values.networking.type }}
  ports:
    - port: {{ .Values.networking.cloudshell.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cloudshell.selectorLabels" . | nindent 4 }}
