apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "library-chart.fullname" . }}-catalog
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
data:
  tpch.properties: |
    connector.name=tpch
    tpch.splits-per-node=4
  tpcds.properties: |
    connector.name=tpcds
    tpcds.splits-per-node=4
{{ $endpoint:= .Values.s3.endpoint }} 
{{ $namespace:= .Release.Namespace }}
{{ $hive:= .Values.discovery.hive }}
{{ $mongodb:= .Values.discovery.mongodb }}
{{ $postgres:= .Values.discovery.postgres }}
{{ $username:= .Values.security.username }} 
{{ $password:= .Values.security.password }}     
{{ range $index, $service := (lookup "v1" "Service" $namespace "").items }}
{{- if (index $service "metadata" "labels") }}
{{- if (index $service "metadata" "labels" "helm.sh/chart") }}
{{ $data := dict "mongodb" $mongodb "service" $service "namespace" $namespace "index" $index "username" $username "password" $password}}
{{- template "connector.mongodb" $data -}}
{{ $data := dict "hive" $hive "service" $service "namespace" $namespace "index" $index "endpoint" $endpoint }}
{{- template "connector.hive" $data -}}
{{ $data := dict "postgres" $postgres "service" $service "namespace" $namespace "index" $index}}
{{- template "connector.postgres" $data -}}
{{- end }}
{{- end }}
{{- end }}
{{- range $catalogName, $catalogProperties := .Values.additionalCatalogs }}
  {{ $catalogName | lower }}.properties: |
    {{- $relname :=  $catalogProperties | trim | split " " }}
    {{- range $prop := $relname }}
    {{-  $prop | nindent 4}}
    {{- end }}
{{- end }}