apiVersion: v1
kind: Service
metadata:
  name: {{ include "openrefine.fullname" . }}
  labels:
    {{- include "openrefine.labels" . | nindent 4 }}
spec:
  type: {{ .Values.networking.type }}
  ports:
    - port: {{ .Values.networking.openrefine.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "openrefine.selectorLabels" . | nindent 4 }}
