mongodb: 
  fullnameOverride: mongodb
  architecture: replicaset
  image:
    tag: "4.4"
  auth:
    rootPassword: changeme
    username: username
    password: changeme
    database: defaultdb

fullnameOverride: mongodb
