{{- if contains "thrift" (include "hiveMetastore.configmap" .)  }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{- printf "%s-configmaphive" (include "jupyter.fullname" .) }}
  labels:
    {{- include "jupyter.labels" . | nindent 4 }}
data:
  hive-site.xml: |
    {{- include "hiveMetastore.configmap" . | nindent 4 }}
{{- end }}