{{- $fullName := include "jupyter.fullname" . -}}
{{- $volumeName := printf "%s-%s" $fullName "data" | trunc 63 | trimSuffix "-" -}}
{{- $initContainerName := printf "%s-%s" $fullName "init-data" | trunc 63 | trimSuffix "-" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jupyter.fullname" . }}
  labels:
    {{- include "jupyter.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "jupyter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "jupyter.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: home
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "jupyter.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: {{$volumeName}}
          emptyDir: {}
        {{- if .Values.discovery.hive }}
        - name: hive-config
          configMap:
            name: {{ include "jupyter.configMapNameHive" . }}
        {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jupyter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      subdomain: {{ include "jupyter.fullname" . }}
      hostname: jupyter
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- if .Values.service.image.custom.enabled }}
          image: "{{ .Values.service.image.custom.version }}"
          {{- else }}
          image: "{{ .Values.service.image.version }}"
          {{- end }}          
          command: ["/bin/sh","-c"]
          args: ["/data/{{ .Values.init.filename}} start.sh jupyter-lab --notebook-dir=/home/$(NB_USER)/work --NotebookApp.token='$(PASSWORD)'"]
          imagePullPolicy: {{ .Values.service.image.pullPolicy }}
          env:
            - name: KUBERNETES_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NB_USER
              value: {{ .Values.service.user }}
            - name: PASSWORD
              value: {{ .Values.security.password }}
            {{- if .Values.init.personnalInit }}
            - name: PERSONNAL_INIT_SCRIPT
              value: {{ .Values.init.personnalInit }}
            {{- end }}   
            {{- if .Values.environment.root }}
            - name: GRANT_SUDO
              value: "yes"
            {{- end }}          
          envFrom: 
            {{- if .Values.environment.s3 }}
            - configMapRef:
                name: {{ include "jupyter.configMapNameS3" . }}
            {{- end }}
            {{- if .Values.environment.vault }}
            - configMapRef:
                name: {{ include "jupyter.configMapNameVault" . }}
            {{- end }}
            {{- if .Values.environment.git }}
            - configMapRef:
                name: {{ include "jupyter.configMapNameGit" . }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8888
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          startupProbe:
            httpGet:
              path: /
              port: http
            {{- toYaml .Values.startupProbe | nindent 12 }}     
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /data
              name: {{$volumeName}}
            - mountPath: /home/{{ .Values.service.user}}/work
              name: home
            {{- if .Values.discovery.hive }}
            - name: hive-config
              mountPath: /opt/hive/conf/hive-site.xml
              subPath: hive-site.xml
            {{- end }}
      initContainers:
        - name: standard-init
          image: "busybox"
          command: ["/bin/sh","-c"]
          args: ["wget -O /data/{{ .Values.init.filename}} {{ .Values.init.standardInit}} && chmod +x /data/{{ .Values.init.filename}}"]
          volumeMounts:
          - mountPath: /data
            name: {{$volumeName}}          
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
