apiVersion: v1
kind: Service
metadata:
  name: {{ include "jupyter.fullname" . }}
  labels:
    {{- include "jupyter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.networking.type }}
  {{- if .Values.networking.clusterIP }}
  clusterIP: {{ .Values.networking.clusterIP }}
  {{- end }}
  ports:
    - port: {{ .Values.networking.jupyter.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.service.sparkui }}
    - port: {{ .Values.networking.sparkui.port }}
      targetPort: 4040
      protocol: TCP
      name: sparkui
    {{- end }}
  selector:
    {{- include "jupyter.selectorLabels" . | nindent 4 }}
