apiVersion: v1
kind: Service
metadata:
  name: {{ include "jupyter.fullname" . }}
  labels:
    {{- include "jupyter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.networking.type }}
  ports:
    - port: {{ .Values.networking.jupyter.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "jupyter.selectorLabels" . | nindent 4 }}
