{{- if .Values.environment.s3 -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mlflow.configMapNameS3" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
data:
  AWS_ACCESS_KEY_ID: "{{ .Values.s3.accessKeyId }}"
  AWS_S3_ENDPOINT: "{{ .Values.s3.endpoint }}"
  AWS_DEFAULT_REGION: "{{ .Values.s3.defaultRegion }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.s3.secretAccessKey }}"
  AWS_SESSION_TOKEN: "{{ .Values.s3.sessionToken }}"
  MLFLOW_S3_ENDPOINT_URL: "https://{{ .Values.s3.endpoint }}"

  {{- end }}