{{- if .Values.discovery.postgres -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pgadmin.fullname" . }}
  labels:
    {{- include "pgadmin.labels" . | nindent 4 }}
data:
  servers.json: |-
    {{- include "pgadmin.configmap" . | nindent 4 }}
