apiVersion: v1
kind: Service
metadata:
  name: {{ include "jena.fullname" . }}
  labels:
    {{- include "jena.labels" . | nindent 4 }}
spec:
  type: {{ .Values.networking.type }}
  ports:
    - port: {{ .Values.networking.jena.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "jena.selectorLabels" . | nindent 4 }}
