{{- if .Values.ingress.enabled -}}
{{- $fullName := include "neo4j.fullname" . -}}
{{- $svcPortUI := .Values.networking.neo4jUI.port -}}
{{- $svcPortBolt := .Values.networking.neo4jBolt.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "neo4j.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostnameUI | quote }}
        - {{ .Values.ingress.hostnameBolt | quote }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.hostnameUI | quote }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPortUI }}
    - host: {{ .Values.ingress.hostnameBolt | quote }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPortBolt }}
{{- end }}