{{- if .Values.security.networkPolicy.enable -}}
{{- if .Values.ingress.enabled -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "neo4j.fullname" . }}-2
spec:
  podSelector:
    matchLabels:
      {{- include "neo4j.selectorLabels" . | nindent 6 }}
  ingress:
  - from:
    {{- toYaml .Values.security.networkPolicy.from | nindent 4 }}
  policyTypes:
  - Ingress
{{- end }}
{{- end }} 