apiVersion: v1
kind: Service
metadata:
  name: {{ include "neo4j.fullname" . }}
  labels:
    {{- include "neo4j.labels" . | nindent 4 }}
spec:
  type: {{ .Values.networking.type }}
  ports:
    - port: {{ .Values.networking.neo4jUI.port }}
      targetPort: ui
      protocol: TCP
      name: ui
    - port: {{ .Values.networking.neo4jBolt.port }}
      targetPort: bolt
      protocol: TCP
      name: bolt
  selector:
    {{- include "neo4j.selectorLabels" . | nindent 4 }}
