apiVersion: v1
kind: Service
metadata:
  name: {{ include "vscode.fullname" . }}
  labels:
    {{- include "vscode.labels" . | nindent 4 }}
spec:
  type: {{ .Values.networking.type }}
  ports:
    - port: {{ .Values.networking.vscode.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vscode.selectorLabels" . | nindent 4 }}
